eureka:
  instance:
    hostname: peer1.jinghanit.com
    registerPort: 9999
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.registerPort}/eureka/

server:
  port: 8080

spring:
  application:
    name: routing-zuul

#serviceId 对应各个微服务定义的spring.application.name
zuul:
  routes:
    user:
      path: /jinghan-user/**
      serviceId: jinghan-user
    shop:
      path: /jinghan-shop/**
      serviceId: jinghan-shop

## http://localhost:8080/jinghan-user/api/user/save?userName=userName&token=token
## http://localhost:8080/jinghan-shop/api/shop/save?shopName=shopName&token=token